name: Email Server Integration Test

on:
  push:
jobs:
  test-email-server:
    runs-on: ubuntu-latest

    env:
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      SENDGRID_FROM_EMAIL: devsendgridtesting@gmail.com
      REDIS_NAME: redis_testing
      PROXY_DOMAIN: dev.tsaxking.com
      SERVER_PORT: 5000

    timeout-minutes: 5
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: v22.12.0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.13.1

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Start email server (background)
        run: |
          nohup pnpm start > server.log 2>&1 &
          echo $! > server.pid
          sleep 5  # give server time to start

      - name: Run test script
        run: pnpm test

      - name: Stop email server
        if: always()
        run: |
          if [ -f server.pid ]; then
            kill $(cat server.pid) || echo "Server already stopped"
            rm server.pid
          fi
